"""add title to shift date

Revision ID: e9af36e7ad2b
Revises: 63d2cfa3c79e
Create Date: 2021-04-07 00:52:19.617736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9af36e7ad2b'
down_revision = '63d2cfa3c79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contacts', 'clients', ['company_id'], ['id'])
    op.create_foreign_key(None, 'positions', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'contacts', ['contact_id'], ['id'])
    op.add_column('shift_dates', sa.Column('title', sa.String(length=150), nullable=True))
    op.create_foreign_key(None, 'shift_dates', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'shifts', 'shift_dates', ['shift_date_id'], ['id'])
    op.create_foreign_key(None, 'shifts', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'versions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'versions', type_='foreignkey')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_constraint(None, 'shift_dates', type_='foreignkey')
    op.drop_column('shift_dates', 'title')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    # ### end Alembic commands ###
